export { ReactComponent as Home } from './home.svg';
export { ReactComponent as Portfolio } from './portfolio.svg';
export { ReactComponent as Ranking } from './ranking.svg';
export { ReactComponent as Record } from './record.svg';
export { ReactComponent as Logo } from './logo.svg';
export { ReactComponent as Pencil } from './pencil.svg';
export { ReactComponent as Google } from './Google.svg';
export { ReactComponent as Kakao } from './Kakao.svg';
export { ReactComponent as Left } from './chevron-left.svg';
